services:

  db:
    image: postgres:16
    container_name: alumnosdb
    environment:
      POSTGRES_DB: alumnosdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d alumnosdb"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build: .
    container_name: alumnos-api
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/alumnosdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      DD_AGENT_HOST: datadog
      DD_SERVICE: gestion-alumnos
      DD_ENV: dev
      DD_LOGS_INJECTION: "true"
    depends_on:
      db:
        condition: service_healthy
      datadog:
        condition: service_started

  datadog:
    image: datadog/agent:latest
    container_name: datadog-agent
    environment:
      DD_API_KEY: ${DD_API_KEY}
      DD_SITE: us5.datadoghq.com
      DD_APM_ENABLED: "true"
      DD_APM_NON_LOCAL_TRAFFIC: "true"
      DD_LOGS_ENABLED: "true"
      DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL: "true"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
    ports:
      - "8126:8126"

volumes:
  postgres_data:
